import { ArrowUpRight, CheckCircle2, Clock3, LayoutGrid, Plus, SlidersHorizontal } from "lucide-react";
import type { DashboardPage } from "@/lib/dashboard-pages";

export function DashboardSectionPage({ page }: { page: DashboardPage }) {
  return <div className="min-h-[calc(100vh-56px)] bg-[#121212] px-5 py-8 text-[#f4f4f1] lg:px-10">
    <div className="mx-auto max-w-[1180px]">
      <header className="border-b border-white/[0.08] pb-7"><p className="text-xs font-medium text-[#9a8fff]">{page.eyebrow}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.045em]">{page.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#a5a5a5]">{page.description}</p><div className="mt-6 flex gap-2"><button className="inline-flex items-center gap-2 rounded-lg bg-[#f4f4f1] px-3 py-2 text-xs font-semibold text-[#171717]"><Plus size={15} />{page.primaryAction}</button><button className="inline-flex items-center gap-2 rounded-lg border border-white/[0.11] px-3 py-2 text-xs font-medium text-[#d5d5d5] hover:bg-white/[0.05]"><SlidersHorizontal size={15} />{page.secondaryAction}</button></div></header>
      <section className="mt-7 grid gap-3 md:grid-cols-3">{page.metrics.map((metric) => <div key={metric.label} className="rounded-xl border border-white/[0.08] bg-[#191919] p-4"><p className="text-xs text-[#939393]">{metric.label}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em]">{metric.value}</p><p className="mt-2 text-xs leading-5 text-[#8a8a8a]">{metric.copy}</p></div>)}</section>
      <section className="mt-7 grid gap-4 xl:grid-cols-2">{page.panels.map((panel) => <div key={panel.title} className="rounded-xl border border-white/[0.08] bg-[#191919]"><div className="flex items-center gap-2 border-b border-white/[0.08] px-4 py-3"><LayoutGrid size={15} className="text-[#9a8fff]"/><h2 className="text-sm font-medium">{panel.title}</h2></div><div className="p-2">{panel.rows.map((row) => <div key={`${panel.title}-${row.label}`} className="flex items-center justify-between rounded-lg px-3 py-3 hover:bg-white/[0.04]"><span><span className="block text-sm text-[#e7e7e7]">{row.label}</span><span className="mt-1 block text-xs text-[#858585]">{row.meta}</span></span><span className="flex items-center gap-2 text-xs font-medium text-[#c9c1ff]">{row.value}<ArrowUpRight size={14}/></span></div>)}</div></div>)}</section>
      <section className="mt-7 rounded-xl border border-white/[0.08] bg-[#191919]"><div className="flex items-center gap-2 border-b border-white/[0.08] px-4 py-3"><Clock3 size={15} className="text-[#9a8fff]"/><h2 className="text-sm font-medium">Recent activity</h2></div><div className="p-2">{page.activity.map((item) => <div key={`${item.title}-${item.time}`} className="flex items-center justify-between gap-4 rounded-lg px-3 py-3 hover:bg-white/[0.04]"><span className="flex gap-3"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#8cdbb6]"/><span><span className="block text-sm">{item.title}</span><span className="mt-1 block text-xs text-[#858585]">{item.detail}</span></span></span><span className="shrink-0 text-xs text-[#777]">{item.time}</span></div>)}</div></section>
    </div>
  </div>;
}
