import { ArrowUpRight, CheckCircle2, CircleDollarSign, Clock3, FileText, LayoutGrid, Settings2 } from "lucide-react";

type Item = { title: string; detail: string; value?: string };

const content = {
  overview: { eyebrow: "Workspace", title: "Research activity", description: "A quiet view of your ongoing work, sources, and decisions.", metrics: [["Active threads", "4"], ["Source sets", "18"], ["Decisions waiting", "2"]], panels: [["Continue", [{ title: "Laptop comparison", detail: "Waiting for a product selection", value: "Review" }, { title: "AI search evaluation", detail: "Citations are being checked", value: "In progress" }]], ["Recent reports", [{ title: "Developer laptop shortlist", detail: "Four options · cited comparison", value: "Open" }, { title: "Search API landscape", detail: "6 sources · updated today", value: "Open" }]]], activity: ["Clarification answered for laptop comparison", "Two new sources added to AI search evaluation", "Competitor briefing saved to library"] },
  billing: { eyebrow: "Payments", title: "Research spend", description: "Review scoped research costs and approval controls. Purchases remain disabled.", metrics: [["This month", "$18.40"], ["Approved budget", "$40.00"], ["Pending approvals", "1"]], panels: [["Allowances", [{ title: "Product research", detail: "Per-run cap of $5.00", value: "Active" }, { title: "Daily briefing", detail: "Weekday cap of $2.00", value: "Active" }]], ["Controls", [{ title: "New providers", detail: "Ask before any settlement", value: "Required" }, { title: "Checkout actions", detail: "Research handoff only", value: "Blocked" }]]], activity: ["Search provider receipt stored", "Monthly budget refreshed", "Provider approval requested"] },
  tables: { eyebrow: "Operations", title: "Research records", description: "A compact operational view of work that has moved through the research system.", metrics: [["Jobs", "24"], ["Evidence items", "168"], ["Citations", "92"]], panels: [["Recent jobs", [{ title: "Laptop comparison", detail: "Planning · product research", value: "Open" }, { title: "Battery recycling brief", detail: "Completed · cited report", value: "Open" }]], ["Evidence health", [{ title: "Citation coverage", detail: "Claims tied to retrieved evidence", value: "96%" }, { title: "Source diversity", detail: "Independent sources represented", value: "High" }]]], activity: ["Research plan generated", "Evidence retrieval completed", "Report editor flagged one uncertain claim"] },
  profile: { eyebrow: "Settings", title: "Research preferences", description: "Set defaults for how this workspace asks questions, spends, and presents results.", metrics: [["Default budget", "$5.00"], ["Citation policy", "Required"], ["Product mode", "Review first"]], panels: [["Research defaults", [{ title: "Clarifying questions", detail: "Ask when the outcome is ambiguous", value: "On" }, { title: "Source preference", detail: "Prioritize direct and primary sources", value: "On" }]], ["Safety", [{ title: "Payment PIN", detail: "Required for approved payment actions", value: "Configured" }, { title: "Autonomous checkout", detail: "Never run from this workspace", value: "Off" }]]], activity: ["Citation policy updated", "Payment control reviewed", "Research defaults saved"] },
} as const;

export function WorkspacePage({ page }: { page: keyof typeof content }) {
  const data = content[page];
  return <div className="min-h-[calc(100vh-56px)] bg-[#121212] px-5 py-8 text-[#f2f2ef] lg:px-10"><div className="mx-auto max-w-[1180px]"><header className="border-b border-white/[0.08] pb-7"><p className="text-xs font-medium text-[#9a8fff]">{data.eyebrow}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.05em]">{data.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#a6a6a6]">{data.description}</p></header><section className="mt-7 grid gap-3 md:grid-cols-3">{data.metrics.map(([label, value]) => <div key={label} className="rounded-xl border border-white/[0.08] bg-[#191919] p-4"><p className="text-xs text-[#8b8b8b]">{label}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em]">{value}</p></div>)}</section><section className="mt-7 grid gap-4 xl:grid-cols-2">{data.panels.map(([title, items]) => <Panel key={title} title={title} items={items}/>)}</section><section className="mt-7 rounded-xl border border-white/[0.08] bg-[#191919]"><div className="flex items-center gap-2 border-b border-white/[0.08] px-4 py-3"><Clock3 size={15} className="text-[#9a8fff]"/><h2 className="text-sm font-medium">Activity</h2></div><div className="p-2">{data.activity.map((item, index) => <div key={item} className="flex items-center justify-between gap-3 rounded-lg px-3 py-3 hover:bg-white/[0.04]"><span className="flex items-center gap-3 text-sm text-[#d7d7d5]"><CheckCircle2 size={16} className="text-[#8bd7b0]"/>{item}</span><span className="text-xs text-[#777]">{index === 0 ? "Now" : "Today"}</span></div>)}</div></section></div></div>;
}

function Panel({ title, items }: { title: string; items: readonly Item[] }) { const Icon = title === "Controls" || title === "Safety" ? Settings2 : title === "Recent reports" ? FileText : title === "Allowances" ? CircleDollarSign : LayoutGrid; return <div className="rounded-xl border border-white/[0.08] bg-[#191919]"><div className="flex items-center gap-2 border-b border-white/[0.08] px-4 py-3"><Icon size={15} className="text-[#9a8fff]"/><h2 className="text-sm font-medium">{title}</h2></div><div className="p-2">{items.map((item) => <div key={item.title} className="flex items-center justify-between gap-3 rounded-lg px-3 py-3 hover:bg-white/[0.04]"><span><span className="block text-sm text-[#e0e0de]">{item.title}</span><span className="mt-1 block text-xs text-[#858585]">{item.detail}</span></span><span className="flex shrink-0 items-center gap-1 text-xs text-[#b7aff5]">{item.value}<ArrowUpRight size={13}/></span></div>)}</div></div>; }
